import AntiGalactus from '../trips/AntiGalactus';
import Casita from '../trips/Casita';
import Drag from '../trips/Drag';
import Fondos from '../trips/Fondos';
import Noise from '../trips/Noise';
import './App.css';
import Text from '../basics/Text';
import Lights from '../basics/Lights';
import Materials from '../basics/Materials';
import Models from '../basics/Models';
import Particles from '../basics/Particles';
import Physics from '../basics/Physics';
import Raycaster from '../basics/Raycaster';
import Shadows from '../basics/Shadows';
import Textures from '../basics/Textures';
import Three from '../basics/Three';
import InitShader from '../shaders/InitShader';
import SecondShader from '../shaders/SecondShader';
import Patron from '../shaders/Patron';
import PatronDraw from '../shaders/PatronDraw';
import Patron3Combination from '../shaders/Patron3Combination';
import PatronDraw2Gradient from '../shaders/PatronDraw2Gradient';
import Patron4Random from '../shaders/Patron4Random';
import Patron5Circle from '../shaders/Patron5Circle';
import Patron6Angles from '../shaders/Patron6Angles';
import Patron7Noise from '../shaders/Patron7Noise';

function App() {
  return <Patron7Noise />;
  // return <Patron6Angles />;
  // return <Patron5Circle />;
  // return <Patron4Random />;
  // return <Patron3Combination />;
  // return <PatronDraw2Gradient />;
  // return <PatronDraw />;
  // return <Patron />;
  // return <SecondShader />;
  // return <InitShader />;
  // return <Models />;
  // return <Noise />;
  // return <Physics />;
  // return <Raycaster />;
  // return <AntiGalactus />;
  // return <Drag />;
  // return <Particles />;
  // return <Casita />;
  // return <Materials />;
  // return <Fondos />;
}

export default App;
